#! /usr/bin/env python

# TESTING BUILDS   
bld.program(
	features='test',
	target = 'test_numa',
	source = [ 'test_numa.cpp' ],
	includes = ['../include/', bld.env.PREFIX+'/include'],
	lib = [ 'gtest'],
	ldflags=['-lnuma'],
	use=['daoNuma']
	)

bld.program(
	features='test',
	target = 'test_queue',
	source = [ 'test_queue.cpp' ],
	includes = ['../include/', bld.env.PREFIX+'/include',],
	lib = [ 'gtest'],
	ldflags=[ '-L'+ bld.env.PREFIX+'/lib64'],
	)

bld.program(
	features='test',
	target = 'test_log',
	source = [ 'test_log.cpp' ],
	includes = ['../include/', bld.env.PREFIX+'/include',],
	lib = [ 'gtest'],
	ldflags=[ '-L'+ bld.env.PREFIX+'/lib64', '-pthread','-ldaoProto'],
	use=['PROTOBUF', 'ZMQ']
	)

daoLogTest = bld.program(
	source = 'daoLogTest.c',
	target = 'daoLogTest',
	includes = '../include '+os.getenv('DAOROOT')+'/include/',
	linkflags = [ '-L'+os.getenv('DAOROOT')+'/lib/','-L'+os.getenv('DAOROOT')+'/lib64/'],
	ldflags = ['-ldaoBase', '-lpthread', '-lrt', '-lm', '-lncurses'],
	use= 'daoBase',
	cflags = ['-Ofast', '-Wall', '-Wextra', '-Werror', '-pipe', '-fdiagnostics-color=auto'],
	)
		