#! /usr/bin/env python

daoRandWriter = bld.program(
	source = 'daoRandWriter.c',
	target = 'daoRandWriter',
	includes = '../include',
	linkflags = ['-L../build/src/'],
	ldflags = ['-ldaoBase' , '-lpthread', '-lrt', '-lm'],
	cflags = ['-Ofast', '-Wall', '-Wextra', '-pipe'],
	use = 'daoBase'
	)

daoClock = bld.program(
	source = 'daoClock.c',
	target = 'daoClock',
	includes = '../include',
	linkflags = ['-L../build/src/'],
	ldflags = ['-ldaoBase' , '-lpthread', '-lrt', '-lm'],
	cflags = ['-Ofast', '-Wall', '-Wextra', '-pipe'],
	use = 'daoBase'
	)

daoTimeDiff = bld.program(
	source = 'daoTimeDiff.c',
	target = 'daoTimeDiff',
	includes = '../include',
	linkflags = ['-L../build/src/'],
	ldflags = ['-ldaoBase' , '-lpthread', '-lrt', '-lm'],
	cflags = ['-Ofast', '-Wall', '-Wextra', '-pipe'],
	use = 'daoBase'
	)

daoReadWrite = bld.program(
	source = 'daoReadWrite.c',
	target = 'daoReadWrite',
	includes = '../include',
	linkflags = ['-L../build/src/'],
	ldflags = ['-ldaoBase' , '-lpthread', '-lrt', '-lm'],
	cflags = ['-Ofast', '-Wall', '-Wextra', '-pipe'],
	use = 'daoBase'
	)