#!/bin/bash

echo "Stoping DAO DEMO processes"

datestr="$( date -u )"
echo "$datestr"

tmux send-keys -t DEMOtimingStat C-c 2> /dev/null
tmux send-keys -t DEMOtiming C-c 2> /dev/null
tmux send-keys -t DEMORandWriter C-c 2> /dev/null
tmux send-keys -t DEMOClock C-c 2> /dev/null

tmux kill-session -t DEMOtimingStat> /dev/null
tmux kill-session -t DEMOtiming> /dev/null
tmux kill-session -t DEMORandWriter> /dev/null
tmux kill-session -t DEMOClock> /dev/null

echo "Done stoping DAO DEMO process."

