#! /usr/bin/env python

bld.shlib(
	source 		= 'cpp/daoNuma.cpp',
	includes 	= '../include',
	ldflags		= "-lnuma",
	cxxflags 	= ['-Ofast', '-Wall', '-Wextra',  '-march=core-avx2', '-mavx2'],
	target 		= 'daoNuma',
	name   		= 'daoNuma',
	vnum   		= '0.0.1')

bld.shlib(
	source = 'c/dao.c',
	includes = ['../include', '/usr/local/include/'],
	#cflags = ['-Ofast', '-Wall', '-Wextra', '-Werror', '-pipe'],
	cflags = ['-Ofast', '-Wall', '-Wextra', '-pipe', '-fdiagnostics-color=auto', '-fstack-protector', '-g'],
	target = 'dao',
	name   = 'dao',
	vnum   = '0.0.1')