#! /usr/bin/env python

bld.shlib(
	source = 'c/daoBase.c',
	includes = '../include',
	#cflags = ['-Ofast', '-Wall', '-Wextra', '-Werror', '-pipe'],
	cflags = ['-Ofast', '-Wall', '-Wextra', '-pipe'],
	target = 'daoBase',
	name   = 'daoBase',
	vnum   = '0.0.1')


bld.shlib(
	source 		= 'cpp/daoNuma.cpp',
	includes 	= '../include',
	ldflags		= "-lnuma",
	cxxflags	= '-std=c++2a',
	target 		= 'daoNuma',
	name   		= 'daoNuma',
	vnum   		= '0.0.1')

